# Production compose file with self-contained containers
# Usage: docker compose -f compose.prod.yml up -d --build

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: ${REGISTRY:-}voicevault-ui:${VERSION:-latest}
    ports:
      - "${UI_PORT:-3000}:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: ${REGISTRY:-}voicevault-api:${VERSION:-latest}
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - LLM_PROVIDER=${LLM_PROVIDER:-groq}
      - LLM_MODEL=${LLM_MODEL:-llama-3.3-70b-versatile}
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-524288000}
      - PROCESSING_TIMEOUT=${PROCESSING_TIMEOUT:-3600}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    restart: unless-stopped

  worker-download:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: ${REGISTRY:-}voicevault-worker:${VERSION:-latest}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - WORKER_MODE=download
      - WORKER_INTERVAL=${WORKER_INTERVAL:-10}
      - BATCH_SIZE=${BATCH_SIZE:-5}
      - DOWNLOAD_DIR=/app/downloads
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-524288000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    restart: unless-stopped

  worker-asr:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: ${REGISTRY:-}voicevault-worker:${VERSION:-latest}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - WORKER_MODE=asr
      - WORKER_INTERVAL=${WORKER_INTERVAL:-10}
      - BATCH_SIZE=${BATCH_SIZE:-5}
      - ASR_PROVIDER=${ASR_PROVIDER:-groq}
      - ASR_MODEL=${ASR_MODEL:-whisper-large-v3-turbo}
      - LLM_PROVIDER=${LLM_PROVIDER:-groq}
      - LLM_MODEL=${LLM_MODEL:-llama-3.3-70b-versatile}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    restart: unless-stopped